# Builds all the projects in the solution...
.PHONY: all_projects
all_projects: afrikaburn_2010 

# Builds project 'afrikaburn_2010'...
.PHONY: afrikaburn_2010
afrikaburn_2010: 
	make --directory="." --file=afrikaburn_2010.makefile

# Cleans all projects...
.PHONY: clean
clean:
	make --directory="." --file=afrikaburn_2010.makefile clean

