# Builds all the projects in the solution...
.PHONY: all_projects
all_projects: afrikaburn_2017 

# Builds project 'afrikaburn_2017'...
.PHONY: afrikaburn_2017
afrikaburn_2017: 
	make --directory="." --file=afrikaburn_2017.makefile

# Cleans all projects...
.PHONY: clean
clean:
	make --directory="." --file=afrikaburn_2017.makefile clean

